# export PATH := ../z3/bin:$(PATH);
# export PATH := ../FStar/bin:$(PATH);

#verify:
	#fstar.exe --include .. IO.Sig.fstIIO.fst Monitor.fst ILang.fst IIO.CompileTo.ILang.fst MLang.fst ILang.CompileTo.MLang.fst

