# export PATH := ../z3/bin:$(PATH);
# export PATH := ../FStar/bin:$(PATH);

verify:
	fstar.exe --include .. IO.Sig.fst DM.IO.fst DM.IIO.fst DM.IIO.Primitives.fst Monitor.fst ILang.fst IIO.CompileTo.ILang.fst DM.fst

